# -*- coding: utf-8 -*-
"""G02_MidProject_SEC-B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-tSzaxfKVoBzjrfX8SXbWldtVHmsUQQ
"""

class User:
    def __init__(self, username, password):
        self.username = username
        self.password = password

class Admin(User):
    def __init__(self, username, password):
        super().__init__(username, password)
        self.teachers = []
        self.students = []

    def add_teacher(self, username, password, name, teacher_id, class_name, section, contact, address):
        teacher = Teacher(username, password, name, teacher_id, class_name, section, contact, address)
        self.teachers.append(teacher)
        print("Teacher Added Successfully!")

    def add_student(self, username, password, name, roll, class_name, section, parents_name, parents_contact, address):
        student = Student(username, password, name, roll, class_name, section, parents_name, parents_contact, address)
        self.students.append(student)
        print("Student Added Successfully!")

class Teacher(User):
    def __init__(self, username, password, name, teacher_id, class_name, section, contact, address):
        super().__init__(username, password)
        self.name = name
        self.teacher_id = teacher_id
        self.class_name = class_name
        self.section = section
        self.contact = contact
        self.address = address
        self.grades = {}

    def add_grades(self, student_roll, subjects):
        grades = {}
        for subject in subjects:
            grade = int(input(f"{subject}: "))
            grades[subject] = grade
        self.grades[student_roll] = grades
        print("Grade Added Successfully!")

    def take_attendance(self, students):
        for student in students:
            attendance = input(f"Name - {student.name}\nRoll - {student.roll}\nEnter Attendance (P/A): ").strip()
            if attendance not in ['P', 'A']:
                print("Invalid input! Please enter 'P' for Present or 'A' for Absent.")
            else:
                student.attendance = attendance
        print("Attendance Taken Successfully!")

    def print_grades_report(self, student_roll, students):
        student = next((s for s in students if s.roll == student_roll), None)
        if student:
            student_grades = self.grades.get(student_roll, {})
            total_marks = sum(student_grades.values())
            average_grade = total_marks / len(student_grades)
            print(f"===========Grades Report==========")
            print(f"Name: {student.name}  Roll: {student.roll}  Section: {student.section}")
            print(f"Contact: {student.parents_contact}  Class: {student.class_name}")
            print("=" * 50)
            print(f"Subject\t\tGrade")
            print("=" * 50)
            for subject, grade in student_grades.items():
                print(f"{subject}\t\t{grade}")
            print("=" * 50)
            print(f"Total Number\t{total_marks}")
            print(f"Total Grade\t{average_grade:.2f}")
            print("=" * 50)
            print("Grades Report Print Successfully!")
        else:
            print("Student not found.")

    def print_attendance_report(self, students):
        print("=" * 50)
        print("Attendance Report")
        print("=" * 50)
        for student in students:
            print(f"{student.name}\t\t{student.roll}\t\t{student.attendance}")

class Student(User):
    def __init__(self, username, password, name, roll, class_name, section, parents_name, parents_contact, address):
        super().__init__(username, password)
        self.name = name
        self.roll = roll
        self.class_name = class_name
        self.section = section
        self.parents_name = parents_name
        self.parents_contact = parents_contact
        self.address = address
        self.attendance = 'A'

def main():
    admin = Admin("admin1", "password1")

    while True:
        print("\n--------------------------High School Management System--------------------------")
        print("1. Admin")
        print("2. Teacher")
        print("3. Student")
        print("4. Exit")

        choice = input("Please Enter Your Choice (1-4): ")
        if choice == '1':
            admin_menu(admin)
        elif choice == '2':
            teacher_menu(admin)
        elif choice == '3':
            student_menu(admin)
        elif choice == '4':
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please enter a valid option.")

def admin_menu(admin):
    username = input("UserName: ")
    password = input("Password: ")

    if username == admin.username and password == admin.password:
        print("Login Successfully!")
        while True:
            print("\n1. Add Teacher")
            print("2. Add Student")
            print("3. Exit")
            choice = input("Please Enter Your Choice (1-3): ")

            if choice == '1':
                set_username = input("Set UserName: ")
                set_password = input("Set Password: ")
                name = input("Teacher Name: ")
                teacher_id = input("Teacher Id: ")
                class_name = input("Class: ")
                section = input("Section: ")
                contact = input("Contact Number: ")
                address = input("Address: ")
                admin.add_teacher(set_username, set_password, name, teacher_id, class_name, section, contact, address)
            elif choice == '2':
                set_username = input("Set UserName: ")
                set_password = input("Set Password: ")
                name = input("Student Name: ")
                roll = input("Roll: ")
                class_name = input("Class: ")
                section = input("Section: ")
                parents_name = input("Parents Name: ")
                parents_contact = input("Parents Contact Number: ")
                address = input("Address: ")
                admin.add_student(set_username, set_password, name, roll, class_name, section, parents_name, parents_contact, address)
            elif choice == '3':
                print("Exiting...")
                break
            else:
                print("Invalid choice. Please enter a valid option.")
    else:
        print("Login Failed. Please check your username and password.")

def teacher_menu(admin):
    username = input("UserName: ")
    password = input("Password: ")

    for teacher in admin.teachers:
        if username == teacher.username and password == teacher.password:
            print("Login Successfully!")
            while True:
                print("\n1. Add Grades")
                print("2. Take Attendance")
                print("3. Print Grades Report")
                print("4. Print Attendance")
                print("5. Exit")
                choice = input("Please Enter Your Choice (1-5): ")

                if choice == '1':
                    student_roll = input("Student Roll: ")
                    teacher.add_grades(student_roll, ["Bangla", "English", "Math", "Science", "Islam", "Social Science", "Art"])
                elif choice == '2':
                    teacher.take_attendance(admin.students)
                elif choice == '3':
                    student_roll = input("Enter Student Roll For Report: ")
                    teacher.print_grades_report(student_roll, admin.students)
                elif choice == '4':
                    teacher.print_attendance_report(admin.students)
                elif choice == '5':
                    print("Exiting...")
                    break
                else:
                    print("Invalid choice. Please enter a valid option.")

def student_menu(admin):
    username = input("UserName: ")
    password = input("Password: ")

    for student in admin.students:
        if username == student.username and password == student.password:
            print("Login Successfully!")
            while True:
                print("\n1. View Result")
                print("2. Exit")
                choice = input("Please Enter Your Choice (1-2): ")

                if choice == '1':
                    student_roll = input("Enter Student Roll For Report: ")
                    student_info = f"Name: {student.name}  Roll: {student.roll}  Section: {student.section}  Teacher Name: {admin.teachers[0].name}"
                    print("=" * 50)
                    print(f"{student_info}")
                    print("=" * 50)
                    admin.teachers[0].print_grades_report(student_roll, admin.students)
                elif choice == '2':
                    print("Exiting...")
                    break
                else:
                    print("Invalid choice. Please enter a valid option.")
            break
    else:
        print("Login Failed. Please check your username and password.")

if __name__ == "__main__":
    main()